# Generated by Django 2.1.5 on 2020-12-02 09:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='机柜编号')),
                ('position', models.CharField(max_length=80, verbose_name='机柜位置')),
                ('desc', models.TextField(blank=True, default='', verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '机柜信息',
                'verbose_name_plural': '机柜信息',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, verbose_name='键')),
                ('value', models.CharField(max_length=80, verbose_name='值')),
                ('desc', models.CharField(blank=True, default='', max_length=100, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='cmdb.Code')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
            },
        ),
        migrations.CreateModel(
            name='ConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(blank=True, default='', max_length=15, verbose_name='SSH用户名')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='SSH密码')),
                ('private_key', models.CharField(blank=True, default='', max_length=100, verbose_name='密钥路径')),
                ('auth_type', models.CharField(choices=[('private_key', '密钥认证'), ('password', '密码认证')], default='', max_length=30)),
                ('status', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'SSH连接信息',
                'verbose_name_plural': 'SSH连接信息',
            },
        ),
        migrations.CreateModel(
            name='DeviceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='asset_file/%Y/%m', verbose_name='资产文件')),
                ('upload_user', models.CharField(max_length=20, verbose_name='上传人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sys_hostname', models.CharField(blank=True, default='', max_length=150, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, default='', max_length=150, verbose_name='MAC地址')),
                ('sn_number', models.CharField(blank=True, default='', max_length=150, verbose_name='SN号码')),
                ('os_type', models.CharField(blank=True, default='', max_length=150, verbose_name='系统类型')),
                ('device_type', models.CharField(blank=True, default='', max_length=150, verbose_name='设备类型')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('network_type', models.IntegerField(blank=True, null=True, verbose_name='网络类型')),
                ('service_type', models.IntegerField(blank=True, null=True, verbose_name='服务类型')),
                ('operation_type', models.IntegerField(blank=True, null=True, verbose_name='业务类型')),
                ('leader', models.IntegerField(blank=True, null=True, verbose_name='责任人')),
                ('dev_cabinet', models.IntegerField(blank=True, null=True, verbose_name='机柜信息')),
                ('dev_connection', models.IntegerField(blank=True, null=True, verbose_name='连接信息')),
                ('buyDate', models.DateField(default=datetime.datetime.now, verbose_name='购买日期')),
                ('warrantyDate', models.DateField(default=datetime.datetime.now, verbose_name='到保日期')),
                ('desc', models.TextField(blank=True, default='', verbose_name='备注信息')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='cmdb.DeviceInfo')),
            ],
            options={
                'verbose_name': '设备信息',
                'verbose_name_plural': '设备信息',
            },
        ),
        migrations.CreateModel(
            name='DeviceScanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(blank=True, default='', max_length=15, verbose_name='SSH用户名')),
                ('password', models.CharField(blank=True, default='', max_length=80, verbose_name='SSH密码')),
                ('private_key', models.CharField(blank=True, default='', max_length=100, verbose_name='密钥路径')),
                ('auth_type', models.CharField(choices=[('private_key', '密钥认证'), ('password', '密码认证')], default='', max_length=30)),
                ('status', models.CharField(blank=True, default='', max_length=10)),
                ('sys_hostname', models.CharField(blank=True, default='', max_length=150, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, default='', max_length=150, verbose_name='MAC地址')),
                ('sn_number', models.CharField(blank=True, default='', max_length=150, verbose_name='SN号码')),
                ('os_type', models.CharField(blank=True, default='', max_length=150, verbose_name='系统类型')),
                ('device_type', models.CharField(blank=True, default='', max_length=150, verbose_name='设备类型')),
                ('error_message', models.CharField(blank=True, default='', max_length=80, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '扫描信息',
                'verbose_name_plural': '扫描信息',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDeviceInfo',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sys_hostname', models.CharField(blank=True, default='', max_length=150, verbose_name='主机名')),
                ('mac_address', models.CharField(blank=True, default='', max_length=150, verbose_name='MAC地址')),
                ('sn_number', models.CharField(blank=True, default='', max_length=150, verbose_name='SN号码')),
                ('os_type', models.CharField(blank=True, default='', max_length=150, verbose_name='系统类型')),
                ('device_type', models.CharField(blank=True, default='', max_length=150, verbose_name='设备类型')),
                ('hostname', models.CharField(max_length=50, verbose_name='设备地址(IP或域名)')),
                ('network_type', models.IntegerField(blank=True, null=True, verbose_name='网络类型')),
                ('service_type', models.IntegerField(blank=True, null=True, verbose_name='服务类型')),
                ('operation_type', models.IntegerField(blank=True, null=True, verbose_name='业务类型')),
                ('leader', models.IntegerField(blank=True, null=True, verbose_name='责任人')),
                ('dev_cabinet', models.IntegerField(blank=True, null=True, verbose_name='机柜信息')),
                ('dev_connection', models.IntegerField(blank=True, null=True, verbose_name='连接信息')),
                ('buyDate', models.DateField(default=datetime.datetime.now, verbose_name='购买日期')),
                ('warrantyDate', models.DateField(default=datetime.datetime.now, verbose_name='到保日期')),
                ('desc', models.TextField(blank=True, default='', verbose_name='备注信息')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 设备信息',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='devicefile',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.DeviceInfo', verbose_name='设备'),
        ),
    ]
